-- MySQL Script generated by MySQL Workbench
-- Пн 17 дек 2018 18:03:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema storagedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `storagedb` ;

-- -----------------------------------------------------
-- Schema storagedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `storagedb` ;
USE `storagedb` ;

-- -----------------------------------------------------
-- Table `storagedb`.`product_dim`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `storagedb`.`product_dim` ;

CREATE TABLE IF NOT EXISTS `storagedb`.`product_dim` (
  `idproduct` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storagedb`.`provider_dim`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `storagedb`.`provider_dim` ;

CREATE TABLE IF NOT EXISTS `storagedb`.`provider_dim` (
  `provider` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  PRIMARY KEY (`provider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storagedb`.`date_dim`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `storagedb`.`date_dim` ;

CREATE TABLE IF NOT EXISTS `storagedb`.`date_dim` (
  `dateKey` INT NOT NULL,
  `year` INT NULL,
  `month` INT NULL,
  `day_of_month` INT NULL,
  `holiday` TINYINT NULL,
  `weekend` TINYINT NULL,
  `date_time` DATETIME NULL,
  PRIMARY KEY (`dateKey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storagedb`.`category_dim`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `storagedb`.`category_dim` ;

CREATE TABLE IF NOT EXISTS `storagedb`.`category_dim` (
  `idcategory` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storagedb`.`shop_dim`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `storagedb`.`shop_dim` ;

CREATE TABLE IF NOT EXISTS `storagedb`.`shop_dim` (
  `shopKey` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  PRIMARY KEY (`shopKey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storagedb`.`order_dim`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `storagedb`.`order_dim` ;

CREATE TABLE IF NOT EXISTS `storagedb`.`order_dim` (
  `idorder` INT NULL,
  `order_id_key` INT NOT NULL,
  `creation_date` DATETIME NULL,
  `total_cost` DOUBLE NULL,
  PRIMARY KEY (`order_id_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storagedb`.`sales_fact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `storagedb`.`sales_fact` ;

CREATE TABLE IF NOT EXISTS `storagedb`.`sales_fact` (
  `product_dim_productKey` INT NOT NULL,
  `provider_dim_providerKey` INT NOT NULL,
  `date_dim_dateKey` INT NOT NULL,
  `category_dim_categoryKey` INT NOT NULL,
  `shop_dim_shopKey` INT NOT NULL,
  `order_dim_order_id_key` INT NOT NULL,
  `quantity` INT NULL,
  `sell_price` DOUBLE NULL,
  `product_price` DOUBLE NULL,
  PRIMARY KEY (`product_dim_productKey`, `provider_dim_providerKey`, `date_dim_dateKey`, `category_dim_categoryKey`, `shop_dim_shopKey`, `order_dim_order_id_key`),
  CONSTRAINT `fk_fact_sales_product_dim1`
    FOREIGN KEY (`product_dim_productKey`)
    REFERENCES `storagedb`.`product_dim` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_sales_provider_dim1`
    FOREIGN KEY (`provider_dim_providerKey`)
    REFERENCES `storagedb`.`provider_dim` (`provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_sales_date_dim1`
    FOREIGN KEY (`date_dim_dateKey`)
    REFERENCES `storagedb`.`date_dim` (`dateKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_sales_category_dim1`
    FOREIGN KEY (`category_dim_categoryKey`)
    REFERENCES `storagedb`.`category_dim` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_fact_shop_dim1`
    FOREIGN KEY (`shop_dim_shopKey`)
    REFERENCES `storagedb`.`shop_dim` (`shopKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_fact_order_dim1`
    FOREIGN KEY (`order_dim_order_id_key`)
    REFERENCES `storagedb`.`order_dim` (`order_id_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
