-- MySQL Script generated by MySQL Workbench
-- Пн 17 дек 2018 18:09:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema categoriesmart
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `categoriesmart` ;

-- -----------------------------------------------------
-- Schema categoriesmart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `categoriesmart` ;
USE `categoriesmart` ;

-- -----------------------------------------------------
-- Table `categoriesmart`.`shop_popular_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categoriesmart`.`shop_popular_categories` ;

CREATE TABLE IF NOT EXISTS `categoriesmart`.`shop_popular_categories` (
  `popular_categories_id` INT NOT NULL,
  `shop_name` VARCHAR(45) NULL,
  `shop_address` VARCHAR(45) NULL,
  `category_name` VARCHAR(45) NULL,
  `quantity` INT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`popular_categories_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
