-- MySQL Script generated by MySQL Workbench
-- Вт 18 дек 2018 05:05:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shopdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shopdb` ;

-- -----------------------------------------------------
-- Schema shopdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopdb` ;
USE `shopdb` ;

-- -----------------------------------------------------
-- Table `shopdb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopdb`.`order` ;

CREATE TABLE IF NOT EXISTS `shopdb`.`order` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `total_cost` DOUBLE NULL,
  `creation_date` DATETIME NULL,
  PRIMARY KEY (`OrderID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopdb`.`category` ;

CREATE TABLE IF NOT EXISTS `shopdb`.`category` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `creation_date` DATETIME NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopdb`.`provider` ;

CREATE TABLE IF NOT EXISTS `shopdb`.`provider` (
  `ProviderID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `contact` VARCHAR(150) NULL,
  `creation_date` DATETIME NULL,
  PRIMARY KEY (`ProviderID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopdb`.`product` ;

CREATE TABLE IF NOT EXISTS `shopdb`.`product` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `price` DOUBLE NULL,
  `buy_price` DOUBLE NULL,
  `ProviderID` INT NOT NULL,
  `update_date` DATETIME NULL,
  `CategoryID` INT NOT NULL,
  PRIMARY KEY (`ProductID`),
  CONSTRAINT `fk_product_provider1`
    FOREIGN KEY (`ProviderID`)
    REFERENCES `shopdb`.`provider` (`ProviderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `shopdb`.`category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopdb`.`order_product` ;

CREATE TABLE IF NOT EXISTS `shopdb`.`order_product` (
  `OrderProductID` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `sell_price` DOUBLE NULL,
  `discount` INT NULL,
  `ProductID` INT NOT NULL,
  `OrderID` INT NOT NULL,
  PRIMARY KEY (`OrderProductID`),
  CONSTRAINT `fk_order_product_product1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `shopdb`.`product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product_order1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `shopdb`.`order` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
